# Generated by Django 4.2.1 on 2023-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=13)),
                ('Password', models.CharField(max_length=1000)),
                ('UserRole', models.CharField(max_length=100)),
                ('registerdate', models.CharField(max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='studentregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear', models.CharField(max_length=100)),
                ('admissionno', models.IntegerField(default=0)),
                ('admissiondate', models.CharField(max_length=100)),
                ('chooseclass', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('studentid', models.IntegerField(default=0)),
                ('studentname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('aadhaarno', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('subcaste', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('fathereducation', models.CharField(max_length=100)),
                ('fatherdesignation', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=100)),
                ('mothereducation', models.CharField(max_length=100)),
                ('motherdesignation', models.CharField(max_length=100)),
                ('mothertongue', models.CharField(max_length=100)),
                ('dependents', models.CharField(max_length=100)),
                ('annualincome', models.CharField(max_length=100)),
                ('lastschool', models.CharField(max_length=100)),
                ('tcno', models.CharField(max_length=100)),
                ('areaid', models.IntegerField(default=0)),
                ('schoolbusid', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
    ]
