# Generated by Django 4.2.1 on 2023-06-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=100)),
                ('sectionName', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='1', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(max_length=50)),
                ('createdby', models.CharField(max_length=100)),
                ('upadated', models.CharField(max_length=50)),
                ('updatedby', models.CharField(max_length=100)),
                ('deletedon', models.CharField(max_length=50)),
                ('deletedby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Addsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='1', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='1', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='instituteprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutecode', models.IntegerField(default=0)),
                ('nameoftrust', models.CharField(max_length=200)),
                ('institutename', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('cashopeningbalance', models.CharField(max_length=30)),
                ('logo', models.CharField(default='noimage.png', max_length=255)),
                ('currentAyear', models.CharField(max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='Shiva', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='Shiva', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='Shiva', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institutionname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(max_length=50)),
                ('createdby', models.CharField(max_length=100)),
                ('upadated', models.CharField(max_length=50)),
                ('updatedby', models.CharField(max_length=100)),
                ('deletedon', models.CharField(max_length=50)),
                ('deletedby', models.CharField(max_length=100)),
            ],
        ),
    ]
