# Generated by Django 4.2.1 on 2023-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0002_addclass_addsection_calender_instituteprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classconducted', models.CharField(max_length=100)),
                ('workdetails', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='1', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.CharField(max_length=100)),
                ('workdetail', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='1', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('institutionid', models.IntegerField(default=0)),
                ('createdon', models.CharField(max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('loginpage', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(max_length=50)),
                ('createdby', models.CharField(max_length=100)),
                ('upadated', models.CharField(max_length=50)),
                ('updatedby', models.CharField(max_length=100)),
                ('deletedon', models.CharField(max_length=50)),
                ('deletedby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagedate', models.CharField(max_length=100)),
                ('messagetitle', models.CharField(max_length=100)),
                ('messagedetails', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='1', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='instituteprofile',
            new_name='InstitutionProfile',
        ),
        migrations.DeleteModel(
            name='newUser',
        ),
        migrations.AlterField(
            model_name='addsection',
            name='institutedId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calender',
            name='institutedId',
            field=models.CharField(max_length=100),
        ),
    ]
