# Generated by Django 4.2.1 on 2023-06-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0005_remove_userregister_institutionname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeardate', models.CharField(max_length=100)),
                ('institutedId', models.CharField(default='', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='00-00-0000', max_length=50)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('upadated', models.CharField(default='00-00-0000', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='00-00-0000', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='select_liabilities',
            field=models.IntegerField(),
        ),
    ]
