# Generated by Django 4.2.1 on 2023-06-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0006_academymaster_alter_accounthead_select_liabilities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademyMaster',
            new_name='AcademicMaster',
        ),
    ]
