# Generated by Django 4.2.1 on 2023-06-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0008_feestype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstFeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(default='', max_length=200)),
                ('caste', models.CharField(default='', max_length=200)),
                ('feetype', models.CharField(default='', max_length=200)),
                ('fee_for', models.CharField(default='', max_length=200)),
                ('fees', models.CharField(default='', max_length=200)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='classwork',
            old_name='classconducted',
            new_name='classconducted_date',
        ),
        migrations.AddField(
            model_name='classwork',
            name='ChooseClass',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classwork',
            name='ChooseSection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homework',
            name='ChooseClass',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homework',
            name='ChooseSection',
            field=models.CharField(default='', max_length=100),
        ),
    ]
