# Generated by Django 4.2.1 on 2023-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0010_casteoperator_mstsubject_religion_subcaste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicmaster',
            name='isactive',
            field=models.IntegerField(default=1),
        ),
    ]
