# Generated by Django 4.2.1 on 2023-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0012_noticecircular'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl', models.CharField(default='', max_length=200)),
                ('sl', models.CharField(default='', max_length=200)),
                ('tl', models.CharField(default='', max_length=200)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='subjectstaffclassmapping',
            name='classteacher',
            field=models.CharField(default='', max_length=200),
        ),
    ]
