# Generated by Django 4.2.1 on 2023-06-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0014_alter_institutionprofile_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='Subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='aadharimage',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='bloodgroup',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='studentphoto',
            field=models.CharField(default='noimage.png', max_length=100),
        ),
    ]
