# Generated by Django 4.2.1 on 2023-06-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0015_studentregister_subject_studentregister_aadharimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_name', models.CharField(default='', max_length=200)),
                ('minimum_marks', models.CharField(default='', max_length=50)),
                ('maximum_marks', models.CharField(default='', max_length=50)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.IntegerField(default=1)),
            ],
        ),
    ]
