# Generated by Django 4.2.1 on 2023-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0016_mstassesment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='instituteid',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
