# Generated by Django 4.2.1 on 2023-06-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0017_studentregister_instituteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='instituteid',
            new_name='institutionid',
        ),
    ]
