# Generated by Django 4.2.1 on 2023-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0020_mstsubject_optional_mstsubject_subjectcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentid', models.CharField(default='', max_length=200)),
                ('classs', models.CharField(default='', max_length=200)),
                ('section', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('studentid', models.CharField(default='', max_length=200)),
                ('studentname', models.CharField(default='', max_length=200)),
                ('assessmentmarks', models.CharField(default='', max_length=200)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavestatus', models.CharField(default='1', max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('leavedate', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='studentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staffid', models.IntegerField(default='')),
                ('attid_p', models.CharField(max_length=100)),
                ('attid_a', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=100)),
                ('sectionid', models.CharField(max_length=100)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('academicyearid', models.IntegerField(default=1)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
    ]
