# Generated by Django 4.2.1 on 2023-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0022_studentregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='studentid',
            field=models.IntegerField(default=0),
        ),
    ]
