# Generated by Django 4.2.1 on 2023-06-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0024_alter_studentattendance_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='studentid',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
