# Generated by Django 4.2.1 on 2023-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0026_alter_studentattendance_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='attid_a',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='attid_p',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='attendancestatus',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
