# Generated by Django 4.2.1 on 2023-06-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0027_remove_studentattendance_attid_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseheadid', models.CharField(default='', max_length=100)),
                ('paidto', models.CharField(max_length=100)),
                ('paymentdate', models.CharField(max_length=100)),
                ('amountpaid', models.CharField(max_length=100)),
                ('paymentmode', models.CharField(max_length=100)),
                ('paymentdetails', models.CharField(max_length=255)),
                ('instituteid', models.CharField(default='', max_length=100)),
                ('createdby', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.IntegerField(default='')),
            ],
        ),
    ]
