# Generated by Django 4.2.1 on 2023-06-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0030_alter_academicmaster_instituteid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionProfile',
        ),
        migrations.RenameField(
            model_name='subjectstaffclassmapping',
            old_name='mclass',
            new_name='Addclass_id',
        ),
    ]
