# Generated by Django 4.2.1 on 2023-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0031_delete_institutionprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='Addclass_id',
            field=models.IntegerField(),
        ),
    ]
