# Generated by Django 4.2.1 on 2023-06-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0032_alter_subjectstaffclassmapping_addclass_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftrust', models.CharField(max_length=200)),
                ('institutename', models.CharField(max_length=200)),
                ('institutecode', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('cashopeningbalance', models.CharField(max_length=30)),
                ('logo', models.CharField(default='noimage.png', max_length=255)),
                ('currentAyear', models.CharField(max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('createdby', models.CharField(default='ADMIN', max_length=50)),
                ('upadated', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='mstfeestype',
            old_name='caste',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='subjectstaffclassmapping',
            name='Addclass_id',
        ),
        migrations.AddField(
            model_name='subjectstaffclassmapping',
            name='Addclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='academicmaster',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='addclass',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='addsection',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='assessmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstassesment'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.studentregister'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='casteoperator',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='casteoperator',
            name='selectreligion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.religion'),
        ),
        migrations.AlterField(
            model_name='castes',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='ChooseClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='ChooseSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='expensehead',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='expensehead',
            name='expenseheadid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.accounthead'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='ChooseClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='ChooseSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='languagemapping',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created', to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='languagemapping',
            name='fl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slf', to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='languagemapping',
            name='sl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl', to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='languagemapping',
            name='tl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stl', to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='mobilenumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='managementmembers',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='message',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='message',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='mstassesment',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='mstfeedback',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='mstfeedback',
            name='feedback',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='mstfeestype',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='mstsubject',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='noticecircular',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='noticecircular',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='noticecircular',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='noticecircular',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='Staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffid', to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Createdby', to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.studentregister'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='academicyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academicid', to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='caste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.casteoperator'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='chooseclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.religion'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='subcaste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.subcaste'),
        ),
        migrations.AlterField(
            model_name='studentselectedsubject',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='studentselectedsubject',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='studentselectedsubject',
            name='sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='studentselectedsubject',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.studentregister'),
        ),
        migrations.AlterField(
            model_name='studentselectedsubject',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='selectcastes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.casteoperator'),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='selectreligion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.religion'),
        ),
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='academicyearid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster'),
        ),
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='createdby',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='academicmaster',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='addclass',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='addsection',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='casteoperator',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='castes',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='expensehead',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='languagemapping',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='mstassesment',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='mstfeestype',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='mstsubject',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='noticecircular',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='studentselectedsubject',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='subcaste',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='subjectstaffclassmapping',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='instituteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.institutionprofile'),
        ),
    ]
