# Generated by Django 4.2.1 on 2023-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0033_institutionprofile_rename_caste_mstfeestype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementmembers',
            name='createdby',
            field=models.CharField(max_length=50),
        ),
    ]
