# Generated by Django 4.2.1 on 2023-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0035_alter_managementmembers_deletedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='homepage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
