# Generated by Django 4.2.1 on 2023-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0036_userregister_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticecircular',
            name='matter',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='noticecircular',
            name='subject',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
