# Generated by Django 4.2.1 on 2023-06-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0039_alter_subjectstaffclassmapping_addclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='password',
        ),
    ]
