# Generated by Django 4.2.1 on 2023-06-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0041_studentregister_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackstatus', models.CharField(max_length=100)),
                ('instituteid', models.IntegerField(default=1)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.academicmaster')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cid', to='nvsapp.userregister')),
                ('sectionid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection')),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sid', to='nvsapp.userregister')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.studentregister')),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstsubject')),
            ],
        ),
    ]
