# Generated by Django 4.1 on 2023-06-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0042_studentfeeback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='academicyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academicid', to='nvsapp.academicmaster'),
        ),
    ]
