# Generated by Django 4.2.1 on 2023-06-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0043_alter_studentregister_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationname', models.CharField(default='', max_length=100)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('createdby', models.CharField(default='ADMIN', max_length=50)),
            ],
        ),
    ]
