# Generated by Django 4.2.1 on 2023-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0044_mstdesignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstdesignation',
            name='createdby',
            field=models.IntegerField(default=1, max_length=50),
        ),
    ]
