# Generated by Django 4.2.1 on 2023-06-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0046_alter_mstdesignation_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstdesignation'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.mstdesignation'),
        ),
    ]
