# Generated by Django 4.2.1 on 2023-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0047_alter_logindetails_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstdesignation',
            name='designationname',
            field=models.CharField(max_length=100),
        ),
    ]
