# Generated by Django 4.2.1 on 2023-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0049_rename_staffid_studentattendance_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavestaff',
            name='leavedate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='subject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
