# Generated by Django 4.2.1 on 2023-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0050_alter_leavestaff_leavedate_alter_leavestaff_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavestaff',
            old_name='createdby',
            new_name='createdby_id',
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='leavestatus',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
