# Generated by Django 4.2.1 on 2023-06-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0051_rename_createdby_leavestaff_createdby_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavestaff',
            old_name='createdby_id',
            new_name='createdby',
        ),
    ]
