# Generated by Django 4.2.1 on 2023-06-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0054_remove_timetableschedule_subjectstaffmapid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=100)),
                ('Holticket', models.CharField(default='noimage.png', max_length=100)),
                ('tc', models.CharField(default='noimage.png', max_length=100)),
                ('MarksCard', models.CharField(default='noimage.png', max_length=100)),
                ('CasteCertificate', models.CharField(default='noimage.png', max_length=100)),
                ('IncomeCertificate', models.CharField(default='noimage.png', max_length=100)),
                ('Aadhaar', models.CharField(default='noimage.png', max_length=100)),
                ('BankPassbook', models.CharField(default='noimage.png', max_length=100)),
                ('Rationcard', models.CharField(default='noimage.png', max_length=100)),
                ('Photho', models.CharField(default='noimage.png', max_length=100)),
                ('Handicappedcertificate', models.CharField(default='noimage.png', max_length=100)),
                ('Medicalcertificate', models.CharField(default='noimage.png', max_length=100)),
                ('Bond', models.CharField(default='noimage.png', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='areaid',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='schoolbusid',
        ),
        migrations.AddField(
            model_name='studentregister',
            name='SchoolBus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='buscharge',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='busfacility',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='discount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='hostelfacility',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='schoolbusroute',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='FeesPaidDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(default='', max_length=100)),
                ('amountpaid', models.IntegerField()),
                ('ddlpaymentmode', models.CharField(max_length=100)),
                ('transactiondetials', models.CharField(max_length=255)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academicyearidfeespaid', to='nvsapp.academicmaster')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userregisterfeespaid', to='nvsapp.userregister')),
                ('instituteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituteidfeespaid', to='nvsapp.institutionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yrschoolfees', models.CharField(default='', max_length=50)),
                ('yrhostelfees', models.CharField(default='', max_length=50)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academicyearid', to='nvsapp.academicmaster')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userregister', to='nvsapp.userregister')),
                ('instituteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituteid', to='nvsapp.institutionprofile')),
            ],
        ),
    ]
