# Generated by Django 4.2.1 on 2023-06-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0055_studentdocument_remove_studentregister_areaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestaff',
            name='academicyearid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lsacademicid', to='nvsapp.academicmaster'),
        ),
        migrations.AddField(
            model_name='leavestaff',
            name='updatedon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cbid', to='nvsapp.userregister'),
        ),
        migrations.AlterField(
            model_name='leavestaff',
            name='instituteid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lsiid', to='nvsapp.institutionprofile'),
        ),
    ]
