# Generated by Django 4.2.1 on 2023-07-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0058_studentleavetoadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='classid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='sectionsid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
        migrations.AlterField(
            model_name='studentleavetoadmin',
            name='classid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addclass'),
        ),
        migrations.AlterField(
            model_name='studentleavetoadmin',
            name='sectionsid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nvsapp.addsection'),
        ),
    ]
