# Generated by Django 4.2.1 on 2023-07-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0060_remove_studentregister_academicyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feespaiddetails',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fpdsid', to='nvsapp.studentregister'),
        ),
        migrations.DeleteModel(
            name='FeesMaster',
        ),
    ]
