# Generated by Django 4.2.1 on 2023-07-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0061_alter_feespaiddetails_studentid_delete_feesmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='feespaiddetails',
            name='classid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fpdclassid', to='nvsapp.addclass'),
        ),
        migrations.AddField(
            model_name='feespaiddetails',
            name='createdonind',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feespaiddetails',
            name='sectionid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fpdsectionid', to='nvsapp.addsection'),
        ),
        migrations.CreateModel(
            name='MstFeesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeshead', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('createdon', models.CharField(default='', max_length=50)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedby', models.CharField(default='', max_length=100)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academicyearidfeeshead', to='nvsapp.academicmaster')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feesheadclass', to='nvsapp.addclass')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userregisterfeeshead', to='nvsapp.userregister')),
                ('instituteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instituteidfeeshead', to='nvsapp.institutionprofile')),
            ],
        ),
    ]
