# Generated by Django 4.2.1 on 2023-07-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0062_feespaiddetails_classid_feespaiddetails_createdonind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehead',
            name='amountpaid',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feespaiddetails',
            name='amountpaid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mstfeeshead',
            name='amount',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mstfeestype',
            name='fees',
            field=models.FloatField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='amount',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='discount',
            field=models.FloatField(default='', max_length=100),
        ),
    ]
