# Generated by Django 4.2.1 on 2023-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0063_alter_expensehead_amountpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='emailid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
