# Generated by Django 4.2.1 on 2023-08-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0069_tempstudentsfeesdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounttopay', models.FloatField()),
                ('createdon', models.CharField(default='', max_length=50)),
                ('createdonind', models.CharField(default='', max_length=50)),
                ('upadatedon', models.CharField(default='', max_length=50)),
                ('deletedon', models.CharField(default='', max_length=50)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdacademicyearidfeespaid', to='nvsapp.academicmaster')),
                ('classid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cdclassid', to='nvsapp.addclass')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cduserregisterfeespaid', to='nvsapp.userregister')),
                ('deletedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cddeletedby', to='nvsapp.userregister')),
                ('instituteid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdinstituteidfeespaid', to='nvsapp.institutionprofile')),
                ('sectionid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cdsectionid', to='nvsapp.addsection')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdsid', to='nvsapp.studentregister')),
                ('updatedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdupdatedby', to='nvsapp.userregister')),
            ],
        ),
    ]
