# Generated by Django 4.2.1 on 2023-08-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0070_challandetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='challandetails',
            name='feestypeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cdfeesheadid', to='nvsapp.mstfeestype'),
        ),
    ]
