# Generated by Django 4.2.1 on 2023-08-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0071_challandetails_feestypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstfeestype',
            name='fee_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mftfees', to='nvsapp.mstfeeshead'),
        ),
        migrations.AlterField(
            model_name='mstfeestype',
            name='fees',
            field=models.FloatField(),
        ),
    ]
