# Generated by Django 4.2.1 on 2023-08-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0072_alter_mstfeestype_fee_for_alter_mstfeestype_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstfeestype',
            name='fee_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mftfees', to='nvsapp.accounthead'),
        ),
    ]
