# Generated by Django 4.2.1 on 2023-08-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0073_alter_mstfeestype_fee_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='mobilenumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
