# Generated by Django 4.2.1 on 2023-08-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0074_alter_userregister_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='challandetails',
            name='collecteddate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='challandetails',
            name='collecteddateind',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='challandetails',
            name='collecterid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cduserregistercollected', to='nvsapp.userregister'),
        ),
        migrations.AddField(
            model_name='challandetails',
            name='collectorcancelchallan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challandetails',
            name='collectorcancelchallanreason',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='challandetails',
            name='paymentstatus',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
