# Generated by Django 4.2.1 on 2023-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0076_feespaiddetails_challanid_delete_logindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempclassfeesdetails',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempinstitutefeesdetails',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempstudentsfeesdetails',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
