# Generated by Django 4.2.1 on 2023-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0077_tempclassfeesdetails_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmarks',
            name='subjectcase',
            field=models.CharField(default='P', max_length=200),
        ),
    ]
