# Generated by Django 4.2.1 on 2023-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0078_assessmentmarks_subjectcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='promotionstatus',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
