# Generated by Django 4.2.1 on 2023-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0079_studentregister_promotionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='promotionstatus',
        ),
        migrations.AddField(
            model_name='assessmentmarks',
            name='subjectresult',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
