# Generated by Django 4.2.1 on 2023-08-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0080_remove_studentregister_promotionstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lbryissuebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField(default=0)),
                ('issued_ISBN_number', models.CharField(default='', max_length=20)),
                ('issuedon', models.CharField(default='', max_length=100)),
                ('bookreturndate', models.CharField(default='', max_length=100)),
                ('returnstatus', models.CharField(default='', max_length=100)),
                ('indianissuedon', models.CharField(default='', max_length=100)),
                ('indianbookreturndate', models.CharField(default='', max_length=100)),
                ('finepaid', models.IntegerField(default=0)),
                ('softdelete', models.IntegerField(default=0)),
                ('academicyearid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iibyid', to='nvsapp.institutionprofile')),
                ('instituteid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liidinstid', to='nvsapp.institutionprofile')),
                ('issuedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liidissedby', to='nvsapp.userregister')),
                ('returnissuedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liidretissedby', to='nvsapp.userregister')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liidsid', to='nvsapp.studentregister')),
            ],
        ),
        migrations.CreateModel(
            name='lbryaddbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktype', models.CharField(default='', max_length=100)),
                ('bookname', models.CharField(default='', max_length=200)),
                ('booktitle', models.CharField(default='', max_length=200)),
                ('ISBNnumber', models.CharField(default='', max_length=100)),
                ('publisher', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=200)),
                ('publishedyear', models.CharField(default='', max_length=200)),
                ('edition', models.CharField(default='', max_length=200)),
                ('publicationcost', models.IntegerField(default=0)),
                ('numberofbooks', models.CharField(default='', max_length=200)),
                ('row', models.CharField(default='', max_length=100)),
                ('shelf', models.CharField(default='', max_length=100)),
                ('rack', models.CharField(default='', max_length=100)),
                ('bookaddedby', models.CharField(default='', max_length=200)),
                ('bookaddedon', models.CharField(default='', max_length=100)),
                ('updatedon', models.CharField(default='', max_length=100)),
                ('updatedby', models.CharField(default='', max_length=100)),
                ('softdelete', models.IntegerField(default=0)),
                ('instituteid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labiid', to='nvsapp.institutionprofile')),
            ],
        ),
    ]
