# Generated by Django 4.2.1 on 2023-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0081_lbryissuebook_lbryaddbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstdesignation',
            name='softdelete',
            field=models.IntegerField(default=0),
        ),
    ]
