# Generated by Django 4.2.1 on 2023-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0082_mstdesignation_softdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstdesignation',
            name='homepage',
            field=models.CharField(default='', max_length=50),
        ),
    ]
