# Generated by Django 4.2.1 on 2023-08-24 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0087_alter_libraryissuebook_instituteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryissuebook',
            name='instituteid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liidinstid', to='nvsapp.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='libraryissuebook',
            name='returnissuedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liidretissedby', to='nvsapp.userregister'),
        ),
    ]
