# Generated by Django 4.2.1 on 2023-08-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0088_alter_libraryissuebook_instituteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryissuebook',
            name='academicyearid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iibyacademicid', to='nvsapp.academicmaster'),
        ),
    ]
