# Generated by Django 4.2.1 on 2023-08-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0091_feesmaster_alter_challandetails_feestypeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmaster',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fmcid', to='nvsapp.addclass'),
        ),
    ]
