# Generated by Django 4.2.1 on 2023-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0096_remove_accounthead_instituteid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('softdelete', models.IntegerField(default=0)),
            ],
        ),
    ]
