# Generated by Django 4.2.1 on 2023-08-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0097_feescategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounthead',
            name='select_liabilities',
        ),
        migrations.AddField(
            model_name='accounthead',
            name='feescategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nvsapp.feescategory'),
        ),
    ]
