# Generated by Django 4.2.1 on 2023-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvsapp', '0098_remove_accounthead_select_liabilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryissuebook',
            old_name='bookreturndate',
            new_name='actualreturndate',
        ),
        migrations.AddField(
            model_name='libraryissuebook',
            name='indianactualreturndate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='libraryissuebook',
            name='returndate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
